######################################################################
# Automatically generated by qmake (2.01a) sex 31. ago 19:09:17 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem08.cpp
