######################################################################
# Automatically generated by qmake (2.01a) qua 12. nov 17:58:53 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
