######################################################################
# Automatically generated by qmake (2.01a) qui 16. out 16:00:23 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
