######################################################################
# Automatically generated by qmake (2.01a) dom set 9 18:04:44 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainDlg.h
SOURCES += main.cpp MainDlg.cpp
