######################################################################
# Automatically generated by qmake (2.01a) sex 31. ago 19:00:16 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem05b.cpp
