######################################################################
# Automatically generated by qmake (2.01a) sáb set 15 13:46:30 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem03.cpp
