######################################################################
# Automatically generated by qmake (2.01a) sáb set 15 16:22:35 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem04.cpp
