######################################################################
# Automatically generated by qmake (2.01a) dom set 9 18:10:38 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem09.cpp
