######################################################################
# Automatically generated by qmake (2.01a) sex 31. ago 18:59:28 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem05a.cpp
