######################################################################
# Automatically generated by qmake (2.01a) ter 11. mar 18:53:09 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += obj.h
SOURCES += obj.cpp

QT -= gui

CONFIG += console

