######################################################################
# Automatically generated by qmake (2.01a) seg 17. nov 18:32:58 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
