######################################################################
# Automatically generated by qmake (2.01a) qua 22. jul 19:30:34 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Editor.h
SOURCES += Editor.cpp main.cpp
