######################################################################
# Automatically generated by qmake (2.01a) dom set 9 18:08:49 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DigitalClock.h
SOURCES += DigitalClock.cpp main.cpp
