######################################################################
# Automatically generated by qmake (2.01a) sex 22. fev 18:28:34 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem01.cpp
