######################################################################
# Automatically generated by qmake (2.01a) ter 8. abr 16:47:42 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dlg.h
FORMS += designer.ui
SOURCES += main.cpp
