######################################################################
# Automatically generated by qmake (2.01a) seg 3. set 10:43:42 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem06.cpp
