######################################################################
# Automatically generated by qmake (2.01a) seg 3. nov 13:01:20 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
DESTDIR = ./
CONFIG -= debug
CONFIG += release console
