######################################################################
# Automatically generated by qmake (2.01a) seg 3. nov 17:29:57 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

#CONFIG -= debug
#CONFIG += release
CONFIG += console

