# #####################################################################
# Automatically generated by qmake (2.01a) qua 25. jul 13:30:27 2007
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWin.h
SOURCES += main.cpp \
    MainWin.cpp
