######################################################################
# Automatically generated by qmake (2.01a) sáb 22. nov 13:18:33 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWidget.h
SOURCES += main.cpp MainWidget.cpp

