######################################################################
# Automatically generated by qmake (2.01a) seg 3. nov 13:21:14 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

CONFIG += console
