######################################################################
# Automatically generated by qmake (2.01a) sex 31. ago 18:57:43 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += exem02.cpp
