######################################################################
# Automatically generated by qmake (2.01a) sex 28. set 09:00:09 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DigitalClock.h MainWidget.h
SOURCES += DigitalClock.cpp main.cpp MainWidget.cpp
