######################################################################
# Automatically generated by qmake (2.01a) seg 20. jul 20:32:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console
