######################################################################
# Automatically generated by qmake (2.01a) qua 12. nov 14:30:39 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QMAKE_CLEAN += $(DESTDIR_TARGET)
