######################################################################
# Automatically generated by qmake (2.01a) qui 11. out 11:32:04 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ftp.h
SOURCES += main.cpp ftp.cpp

QT = core network

CONFIG += console
CONFIG += debug


