#ifndef DLL_18_01_DLL_GLOBAL_H
#define DLL_18_01_DLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLL_08_01_DLL_LIBRARY)
		// ESTOU COMPILANDO ESTA DLL
#  define DLL_08_01_DLLSHARED_EXPORT Q_DECL_EXPORT
#else
		// ESTOU COMPILANDO UM CLIENTE DESTA DLL
#  define DLL_08_01_DLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLL_18_01_DLL_GLOBAL_H
