######################################################################
# Automatically generated by qmake (2.01a) dom set 23 18:26:33 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainDlg.h
SOURCES += main.cpp MainDlg.cpp
